# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Soyons green ! Il est possible d’effectuer des pushes sans faire appel à Travis. Pour ceci, il faut que les commits contenus dans le push possèdent la chaine de caractère [ci skip] dans leur message de commit. Par exemple
#commit -m 'Ceci est un message [ci skip]'


language: R
cache: packages
warnings_are_errors: false

os:
  - linux
  - osx


#, which version of your R package to test
#r:
#  - oldrel
#  - release
#  - devel

notifications:
  email:
    on_success: change
    on_failure: change

## dependencies that need to be installed beforehand if any
# a priori pas besoin de ca : sudo: true
before_install:
 - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libudunits2-dev libgdal-dev ;fi
 - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install udunits ; fi
#addons:
#  apt:
#    packages:
#     - libudunits2-dev

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings
